### ISSUE TITLE
##[error]Version in "./docker-compose.yml" is unsupported. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

### ISSUE THREAD

**Issue by milla** [Microsoft/vsts-docker#46]
I used version: '2' in docker-compose.yml, yet got the following error
```
Building travel.openapi.references.web
Traceback (most recent call last):
File "docker-compose", line 3, in <module>
File "compose\cli\main.py", line 64, in main
File "compose\cli\main.py", line 116, in perform_command
File "compose\cli\main.py", line 223, in build
File "compose\project.py", line 313, in build
File "compose\service.py", line 804, in build
File "site-packages\docker\api\build.py", line 215, in build
File "site-packages\docker\utils\decorators.py", line 47, in inner
File "site-packages\docker\api\client.py", line 179, in _post
File "site-packages\requests\sessions.py", line 522, in post
File "site-packages\requests\sessions.py", line 475, in request
File "site-packages\requests\sessions.py", line 596, in send
File "site-packages\requests\adapters.py", line 423, in send
File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
File "httplib.py", line 1042, in request
File "httplib.py", line 1082, in _send_request
File "httplib.py", line 1038, in endheaders
File "httplib.py", line 886, in _send_output
File "httplib.py", line 855, in send
File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
File "site-packages\docker\transport\npipesocket.py", line 159, in sendall
File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
File "site-packages\docker\transport\npipesocket.py", line 154, in send
pywintypes.error: (232, 'WriteFile', 'The pipe is being closed.')
Failed to execute script docker-compose
```

I've managed to solve this by finding out the version shall be changed to '2.1' as below,  now build goes fine. 

```
version: '2.1'

services:
  travel.openapi.references.web:
    image: travel.openapi.references.web
    build:
      context: ./src/Travel.OpenAPI.References.Web
      dockerfile: Dockerfile
```

But the problem is, when a release followed with the command below, 

```
docker login -u $(docker.username) -p $(docker.password) $(docker.registry) &&cd  deploy&&tail docker-compose.yml&&docker-compose --version&&docker --version&&docker-compose pull
```

the following error throws out,

```
2017-05-27T06:05:08.6899235Z ==============================================================================
2017-05-27T06:05:08.6899235Z Task         : SSH
2017-05-27T06:05:08.6899235Z Description  : Run shell commands or a script on a remote machine using SSH
2017-05-27T06:05:08.6899235Z Version      : 0.115.0
2017-05-27T06:05:08.6899235Z Author       : Microsoft Corporation
2017-05-27T06:05:08.6899235Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkId=821892)
2017-05-27T06:05:08.6899235Z ==============================================================================
2017-05-27T06:05:09.0525365Z Trying to setup SSH connection to ********@xxxxx
2017-05-27T06:05:09.6798055Z Successfully connected.
2017-05-27T06:05:09.6798055Z docker login -u xxx-p xxx xxx.azurecr.io &&cd  deploy&&tail docker-compose.yml&&docker-compose --version&&docker --version&&docker-compose pull
2017-05-27T06:05:10.8771453Z Login Succeeded
2017-05-27T06:05:10.8771453Z 
2017-05-27T06:05:10.8781425Z       context: .\src\Travel.OpenAPI.References.Web
2017-05-27T06:05:10.8781425Z       dockerfile: Dockerfile
2017-05-27T06:05:10.8781425Z     image: xxx.azurecr.io/travel.openapi.references.web@shaxxxx
2017-05-27T06:05:10.8781425Z     labels:
2017-05-27T06:05:10.8781425Z       com.microsoft.acs.dcos.marathon.healthcheck.path: /
2017-05-27T06:05:10.8781425Z     ports:
2017-05-27T06:05:10.8781425Z     - 5000:80
2017-05-27T06:05:10.8781425Z version: '2.1'
2017-05-27T06:05:10.8781425Z volumes: {}
2017-05-27T06:05:10.8781425Z 
2017-05-27T06:05:10.8781425Z 
2017-05-27T06:05:10.8781425Z docker-compose version 1.6.2, build 4d72027
2017-05-27T06:05:10.8781425Z 
2017-05-27T06:05:10.8781425Z Docker version 17.05.0-ce, build 89658be
2017-05-27T06:05:10.8781425Z 
2017-05-27T06:05:11.1658050Z For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
2017-05-27T06:05:11.1658050Z 
2017-05-27T06:05:11.1718471Z ##[error]Version in "./docker-compose.yml" is unsupported. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
2017-05-27T06:05:11.1718471Z For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
2017-05-27T06:05:11.1718471Z 
2017-05-27T06:05:11.1886353Z ##[error]Command docker login -u xx-p xxx xxx.azurecr.io &&cd  deploy&&tail docker-compose.yml&&docker-compose --version&&docker --version&&docker-compose pull exited with code 1.
2017-05-27T06:05:11.2811667Z ##[section]Finishing: Run shell commands on remote machine
2017-05-27T06:05:11.2861670Z ##[section]Finishing: Release
```

A new docker-compose.yml file generated somehow after that build is like below,

```
networks: {}
services:
  travel.openapi.references.web:
    build:
      context: .\src\Travel.OpenAPI.References.Web
      dockerfile: Dockerfile
    image: xxxxx.azurecr.io/travel.openapi.references.web@sha256:xxxxx
    labels:
      com.microsoft.acs.dcos.marathon.healthcheck.path: /
    ports:
    - 5000:80
version: '2.1'
volumes: {}

```
But I can run this command `docker-compose pull` with the yml files locally with compose version 1.11.2 successfully. Is this error related to the compose version? Why is the compose file regenerated as above?

**Comment by stepro** [comment]
Version 1.6.2 of the docker-compose CLI does not support version 2.1 docker-compose file format - you will need to upgrade to 1.11.2 (or later, 1.13.0 is the latest).

I'm not sure what would cause your docker-compose.yml file to be rewritten unless a previous task in your pipeline is doing it. There are some Docker tasks that combine configuration from multiple compose files and write out a single one by running "docker-compose config". According to the output above, this appears to be what is happening as I see a port configuration showing up that wasn't in your original docker-compose.yml file. I wonder if you have a task configured that is actually overwriting your original file during the build? If so, you should change that task so the output file is not the same as your original file.

**Comment by milla** [comment]
@stepro Thank you, by leveraging another "docker compose" VSTS Build task from "Docker Integration" tool, now the problem's gone.
